image: node:12-buster-slim

stages:
  - prepare
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/


build-pwa:
  stage: build
  script:
    - quasar build -m pwa
