image: node:12-buster-slim

stages:
  - build

cache:
  paths:
    - node_modules/

build-pwa:
  stage: build
  variables:
    PATH: '$PATH:/app/node_modules/.bin'
  script:
    - npm install
    - quasar build -m pwa
  artifacts:
    paths:
      - node_modules/
